# Generated by Django 5.2.12 on 2026-03-15 23:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('shift', models.CharField(max_length=20)),
                ('building', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=20)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('owner', models.CharField(max_length=120)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('At Risk', 'At Risk'), ('Blocked', 'Blocked'), ('Completed', 'Completed')], default='Active', max_length=20)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='RoleProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('over_threshold', models.PositiveIntegerField(default=90)),
                ('qualified_threshold', models.PositiveIntegerField(default=75)),
                ('improve_threshold', models.PositiveIntegerField(default=60)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekly_availability', models.JSONField(blank=True, default=list)),
                ('allowed_buildings', models.JSONField(blank=True, default=list)),
                ('max_concurrent_projects', models.PositiveIntegerField(default=1)),
                ('time_off', models.JSONField(blank=True, default=list)),
                ('unavailable_ranges', models.JSONField(blank=True, default=list)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='availability', to='planner.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40, unique=True)),
                ('evaluator', models.CharField(max_length=120)),
                ('date', models.DateField()),
                ('strengths', models.JSONField(blank=True, default=list)),
                ('weaknesses', models.JSONField(blank=True, default=list)),
                ('action_plan', models.TextField(blank=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='planner.employee')),
            ],
            options={
                'ordering': ['date', 'code'],
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='assigned_projects',
            field=models.ManyToManyField(blank=True, related_name='assigned_employees', to='planner.project'),
        ),
        migrations.CreateModel(
            name='ProjectShiftConstraint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift', models.CharField(max_length=20)),
                ('min_required', models.PositiveIntegerField(default=0)),
                ('max_allowed', models.PositiveIntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_constraints', to='planner.project')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planner.roleprofile')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectBuildingConstraint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building', models.CharField(max_length=20)),
                ('min_required', models.PositiveIntegerField(default=0)),
                ('max_allowed', models.PositiveIntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='building_constraints', to='planner.project')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planner.roleprofile')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='allowed_roles',
            field=models.ManyToManyField(blank=True, related_name='eligible_projects', to='planner.roleprofile'),
        ),
        migrations.AddField(
            model_name='employee',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='planner.roleprofile'),
        ),
        migrations.CreateModel(
            name='RoleSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight_override', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('min_value_override', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planner.roleprofile')),
            ],
            options={
                'ordering': ['role__name', 'skill__pillar', 'skill__name'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=120, unique=True)),
                ('pillar', models.CharField(max_length=120)),
                ('color', models.CharField(default='#2f69b3', max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('scoring_type', models.CharField(choices=[('Score out of 100', 'Score out of 100'), ('Scored rubric (1-5)', 'Scored rubric (1-5)'), ('Pass/Fail checklist', 'Pass/Fail checklist')], max_length=50)),
                ('default_weight', models.DecimalField(decimal_places=2, default=1, max_digits=6)),
                ('min_value', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('notes', models.TextField(blank=True)),
                ('roles', models.ManyToManyField(related_name='skills', through='planner.RoleSkill', to='planner.roleprofile')),
            ],
            options={
                'ordering': ['pillar', 'name'],
            },
        ),
        migrations.AddField(
            model_name='roleskill',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planner.skill'),
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('training_type', models.CharField(max_length=80)),
                ('owner', models.CharField(max_length=120)),
                ('pass_score', models.PositiveIntegerField(default=70)),
                ('duration', models.CharField(blank=True, max_length=120)),
                ('linked_skills', models.ManyToManyField(blank=True, related_name='trainings', to='planner.skill')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='trainings',
            field=models.ManyToManyField(blank=True, related_name='employees', to='planner.training'),
        ),
        migrations.CreateModel(
            name='ProjectRoleConstraint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_required', models.PositiveIntegerField(default=0)),
                ('max_allowed', models.PositiveIntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_constraints', to='planner.project')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planner.roleprofile')),
            ],
            options={
                'unique_together': {('project', 'role')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='roleskill',
            unique_together={('role', 'skill')},
        ),
        migrations.CreateModel(
            name='ProjectRequiredSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_value', models.DecimalField(decimal_places=2, max_digits=6)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_skills', to='planner.project')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planner.skill')),
            ],
            options={
                'ordering': ['project__code', 'skill__name'],
                'unique_together': {('project', 'skill')},
            },
        ),
        migrations.CreateModel(
            name='EvaluationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=8)),
                ('status', models.CharField(choices=[('Pass', 'Pass'), ('Fail', 'Fail'), ('Meets Min', 'Meets Min'), ('Below Min', 'Below Min')], max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='planner.evaluation')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planner.skill')),
            ],
            options={
                'ordering': ['skill__pillar', 'skill__name'],
                'unique_together': {('evaluation', 'skill')},
            },
        ),
    ]
